=== aliaksei23/epamTraining_Task02/src/main/resources/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/medicines"
        xmlns:tns="http://www.example.org/medicines"
        elementFormDefault="qualified">

    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="medicine" type="tns:Medicine"/>
    <element name="localMedicine" type="tns:localMedicine" substitutionGroup="tns:medicine"/>
    <element name="importedMedicine" type="tns:importedMedicine" substitutionGroup="tns:medicine"/>

    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="producer" type="string"/>
            <element name="expirationDate" type="gYearMonth"/>
            <element name="analogsList" type="tns:stringList"/>
            <element name="versions">
                <complexType>
                    <sequence>
                        <element name="version" type="tns:Version" maxOccurs="10"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="group" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Antibiotics"/>
                    <enumeration value="Painkillers"/>
                    <enumeration value="Vitamins"/>
                    <enumeration value="Syrop"/>
                    <enumeration value="Powder"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Version">
        <sequence>
            <element name="versionOfProduction" type="string"/>
            <element name="certificate" type="tns:Certificate"/>
            <element name="medicinePackage" type="tns:MedicinePackage"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
    </complexType>

    <complexType name="Certificate">
        <sequence>
            <element name="number" type="int"/>
            <element name="issueDate" type="gYearMonth"/>
            <element name="certificateExpirationDate" type="gYearMonth"/>
            <element name="registeringOrganization" type="string"/>
        </sequence>
    </complexType>

    <complexType name="MedicinePackage">
        <sequence>
            <element name="typeOfPackaging" type="string"/>
            <element name="amountInPackage" type="int"/>
            <element name="price" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Dosage">
        <sequence>
            <element name="drugDosage" type="int"/>
            <element name="frequencyOfAdmission" type="int"/>
        </sequence>
    </complexType>

    <complexType name="localMedicine">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="regionOfProduction" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="importedMedicine">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="countryOfProduction" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="dateFormat">
        <restriction base="gYearMonth">
            <pattern value="2[0-9][0-9][0-9]-(0[1-9])|(1[0-2])"/>
        </restriction>
    </simpleType>

    <simpleType name="stringList">
        <list itemType="string"/>
    </simpleType>
</schema>

=== aliaksei23/epamTraining_Task02/src/test/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns="http://www.example.org/medicines"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org/medicines  medicines.xsd">

    <medicine group="Painkillers" idInPharmacy="m01">
        <name>Analgin</name>
        <producer>BelMed</producer>
        <expirationDate>2050-05</expirationDate>
        <analogsList>Xefocam Ketonal</analogsList>
        <versions>
            <version>
                <versionOfProduction>Tablets</versionOfProduction>
                <certificate>
                    <number>123</number>
                    <issueDate>2020-05</issueDate>
                    <certificateExpirationDate>2024-08</certificateExpirationDate>
                    <registeringOrganization>Organization1</registeringOrganization>
                </certificate>
                <medicinePackage>
                    <typeOfPackaging>Plastins</typeOfPackaging>
                    <amountInPackage>20</amountInPackage>
                    <price>1.4</price>
                </medicinePackage>
                <dosage>
                    <drugDosage>200</drugDosage>
                    <frequencyOfAdmission>3</frequencyOfAdmission>
                </dosage>
            </version>
        </versions>
    </medicine>
    <importedMedicine group="Vitamins" idInPharmacy="im03">
        <name>AlfaVit Energy</name>
        <producer>ForeignerOrganization</producer>
        <expirationDate>2027-08</expirationDate>
        <analogsList>Biorhythm Makrovit</analogsList>
        <versions>
            <version>
                <versionOfProduction>Pills</versionOfProduction>
                <certificate>
                    <number>879</number>
                    <issueDate>2021-08</issueDate>
                    <certificateExpirationDate>2028-05</certificateExpirationDate>
                    <registeringOrganization>Organization4</registeringOrganization>
                </certificate>
                <medicinePackage>
                    <typeOfPackaging>vial</typeOfPackaging>
                    <amountInPackage>50</amountInPackage>
                    <price>12.8</price>
                </medicinePackage>
                <dosage>
                    <drugDosage>150</drugDosage>
                    <frequencyOfAdmission>1</frequencyOfAdmission>
                </dosage>
            </version>
        </versions>
        <countryOfProduction>ForeignerCountry</countryOfProduction>
    </importedMedicine>
    <localMedicine group="Antiviral" idInPharmacy="lm06">
        <name>Arbidol Maximum</name>
        <producer>LocalOrganization</producer>
        <expirationDate>2027-08</expirationDate>
        <analogsList>Arbidol Tamiflu</analogsList>
        <versions>
            <version>
                <versionOfProduction>Capsules</versionOfProduction>
                <certificate>
                    <number>06</number>
                    <issueDate>2020-11</issueDate>
                    <certificateExpirationDate>2027-01</certificateExpirationDate>
                    <registeringOrganization>OrganizationLocal2</registeringOrganization>
                </certificate>
                <medicinePackage>
                    <typeOfPackaging>vial</typeOfPackaging>
                    <amountInPackage>40</amountInPackage>
                    <price>25</price>
                </medicinePackage>
                <dosage>
                    <drugDosage>200</drugDosage>
                    <frequencyOfAdmission>2</frequencyOfAdmission>
                </dosage>
            </version>
        </versions>
        <regionOfProduction>LocalRegion</regionOfProduction>
    </localMedicine>
</medicines>
